spring:
  application:
    name: Book Api
  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: book-api
server:
  port: 8081
logging:
  level:
    com.learning.book.api: INFO