name: Code Quality Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run Checkstyle
        continue-on-error: true # Continue if Checkstyle fails
        run: ./gradlew checkstyleMain
      - name: Upload Checkstyle Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/
      - name: Run PMD
        continue-on-error: true # Continue if PMD fails
        run: ./gradlew pmdMain
      - name: Upload PMD Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: build/reports/pmd/
      - name: Run SpotBugs
        continue-on-error: true # Continue if SpotBugs fails
        run: ./gradlew spotbugsMain
      - name: Upload SpotBugs Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: build/reports/spotbugs/
      - name: Run Tests and JaCoCo
        run: ./gradlew test jacocoTestReport jacocoTestCoverageVerification
      - name: Upload JaCoCo Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/